package com.unispeaking.domain.session;

public enum SessionEventType {
	PROVIDER_SESSION_CREATED,
	PROVIDER_SESSION_UPDATED,
	USER_TRANSCRIPT_COMPLETED,
	AI_TRANSCRIPT_COMPLETED,
	SESSION_PAUSE,
	SESSION_RESUME,
	SESSION_INTERRUPT,
	SESSION_COMPLETE,
	SESSION_ERROR,
	BIND_TIMEOUT,
	UNKNOWN
}
